- backend/demo/src/main/java/com/example/custard/common/BaseResponse.java
- backend/demo/src/main/java/com/example/custard/common/BaseTimeEntity.java
[Http 응답을 통일하기 위한 BaseResponse 추가 데이터가 생성된 시간을 저장하기 위한 BaseTimeEntity 추가
> [Feat] BaseResponse, BaseEntity 추가 

- backend/pom.xml
- backend/src/main/java/com/example/backend/customer/service/CustomerEmailVerifyService.java
- backend/src/main/java/com/example/backend/product/controller/ProductController.java
- backend/src/main/java/com/example/backend/product/model/entity/Product.java
- backend/src/main/java/com/example/backend/product/model/response/GetProductListRes.java
- backend/src/main/java/com/example/backend/product/model/response/GetProductRes.java
- backend/src/main/java/com/example/backend/product/repository/ProductRepository.java
- backend/src/main/java/com/example/backend/product/service/ProductService.java
- backend/src/main/resources/application.yml
- 상품 목록 조회 기능 추가
- 상품 상세 조회 기능 추가
- 상품 검색 기능 추가(키워드 기반)
> [Feat] Product 기능 구현(#5, #6, #7)

- .idea/compiler.xml
- .idea/encodings.xml
- .idea/jarRepositories.xml
- backend/src/main/java/com/example/backend/orders/controller/OrdersController.java
- backend/src/main/java/com/example/backend/orders/model/entity/GetPortoneRes.java
- backend/src/main/java/com/example/backend/orders/model/entity/Orders.java
- backend/src/main/java/com/example/backend/orders/model/response/GetOrdersCreateRes.java
- backend/src/main/java/com/example/backend/orders/repository/OrdersRepository.java
- backend/src/main/java/com/example/backend/orders/service/OrdersService.java
- backend/src/main/java/com/example/backend/orders/service/PaymentService.java
- 주문 기능 추가
- 아임포트를 이용한 카카오페이 결제 기능 추가
> [Feat] 주문/결제 기능 구현(#8, #9)

- backend/src/main/java/com/example/backend/BackendApplication.java
- backend/src/main/java/com/example/backend/common/BaseResponse.java
- backend/src/main/java/com/example/backend/common/BaseTimeEntity.java
- backend/src/main/java/com/example/backend/orders/model/entity/Orders.java
- backend/src/main/java/com/example/backend/orders/service/OrdersService.java
- 공통된 응답을 위한 BaseResponse 추가
- 데이터 생성/수정된 시간을 저장하는 추상 클래스 BaseTimeEntity 추가
- Orders Entity에 BaseTimeEntity를 상속받게 하는 코드 추가
> [Chore] BaseTimeEntity, BaseResponse 추가

- backend/src/main/java/com/example/backend/answer/model/entity/Answer.java
- backend/src/main/java/com/example/backend/answer/repository/AnswerRepository.java
- backend/src/main/java/com/example/backend/config/CustomAuthenticationProvider.java
- backend/src/main/java/com/example/backend/config/SecurityConfig.java
- backend/src/main/java/com/example/backend/qna/controller/QnaController.java
- backend/src/main/java/com/example/backend/qna/model/entity/Qna.java
- backend/src/main/java/com/example/backend/qna/model/request/PostQnaReadReq.java
- backend/src/main/java/com/example/backend/qna/model/request/PostQnaRegisterReq.java
- backend/src/main/java/com/example/backend/qna/model/response/GetQnaListRes.java
- backend/src/main/java/com/example/backend/qna/model/response/PostQnaReadRes.java
- backend/src/main/java/com/example/backend/qna/model/response/PostQnaRegisterRes.java
- backend/src/main/java/com/example/backend/qna/repository/QnaRepository.java
- backend/src/main/java/com/example/backend/qna/service/QnaService.java
> [Feat] 1:1 문의 기능 구현 (#11, #12, #13)

- backend/src/main/java/com/example/backend/customer/model/entity/Customer.java
- backend/src/main/java/com/example/backend/customer/service/CustomerService.java
- backend/src/main/java/com/example/backend/log/entity/LoginLog.java
- backend/src/main/java/com/example/backend/log/entity/ProductDetailLog.java
- backend/src/main/java/com/example/backend/log/entity/SearchLog.java
- backend/src/main/java/com/example/backend/log/repository/LoginLogRespository.java
- backend/src/main/java/com/example/backend/log/service/LogService.java
- backend/src/main/java/com/example/backend/orders/model/entity/Orders.java
- backend/src/main/java/com/example/backend/orders/service/OrdersService.java
- backend/src/main/java/com/example/backend/product/controller/ProductController.java
- backend/src/main/java/com/example/backend/product/service/ProductService.java
- 로그인 시 로그를 남기는 기능 추가
- 상품, 주문 연관관계 추가
> [Feat] 로그인 로그 기능 추가 (#42) 

- backend/src/main/java/com/example/backend/config/filter/JwtFilter.java
- backend/src/main/java/com/example/backend/customer/model/entity/Customer.java
- backend/src/main/java/com/example/backend/customer/service/CustomerService.java
- backend/src/main/java/com/example/backend/log/entity/ProductDetailLog.java
- backend/src/main/java/com/example/backend/log/entity/SearchLog.java
- backend/src/main/java/com/example/backend/log/repository/ProductDetailLogRespository.java
- backend/src/main/java/com/example/backend/log/repository/SearchLogRepository.java
- backend/src/main/java/com/example/backend/log/service/LoginLogService.java
- backend/src/main/java/com/example/backend/log/service/ProductDetailLogService.java
- backend/src/main/java/com/example/backend/log/service/SearchLogService.java
- backend/src/main/java/com/example/backend/product/controller/ProductController.java
- backend/src/main/java/com/example/backend/product/model/entity/Product.java
- backend/src/main/java/com/example/backend/product/service/ProductService.java
- 일반 사용자가 상품을 상세 조회 할 때 로그를 남기는 기능 추가
- 일반 사용자가 로그인하고 조회하는 경우에만 로그를 남김
- 사용자 정보, 상품 정보, 상품 조회 시간을 저장
- 일반 사용자가 키워드 기반으로 상품을 검색할 때 로그를 남기는 기능 추가
- 일반 사용자가 로그인하고 검색하는 경우에만 로그를 남김
- 사용자 정보, 검색 키워드, 검색 시간을 저장
close #42
> [Feat] 상품 상세 조회 로그, 상품 검색  로그 기능 추가 (#42)

- backend_admin/src/main/java/com/example/backend_admin/admin/model/entity/Admin.java
- backend_admin/src/main/java/com/example/backend_admin/admin/model/response/GetAdminReadRes.java
- backend_admin/src/main/java/com/example/backend_admin/admin/service/AdminService.java
- backend_admin/src/main/java/com/example/backend_admin/coupon/controller/CouponController.java
- backend_admin/src/main/java/com/example/backend_admin/coupon/model/entity/Coupon.java
- backend_admin/src/main/java/com/example/backend_admin/coupon/model/request/PostCouponCreateReq.java
- backend_admin/src/main/java/com/example/backend_admin/coupon/model/response/GetCouponReadRes.java
- backend_admin/src/main/java/com/example/backend_admin/coupon/model/response/PostCouponCreateRes.java
- backend_admin/src/main/java/com/example/backend_admin/coupon/service/CouponService.java
> [Feat] 관리자 coupon 발급 기능 구현 (#62)

- backend/src/main/java/com/example/backend/customer/model/entity/Customer.java
- backend/src/main/java/com/example/backend/customer/service/CustomerService.java
- backend/src/main/java/com/example/backend/orders/service/OrdersService.java
- backend/src/main/java/com/example/backend/product/controller/ProductController.java
- backend_admin/src/main/java/com/example/backend_admin/customer/entity/Customer.java
- backend_admin/src/main/java/com/example/backend_admin/customer/repository/CustomerRepository.java
- backend_admin/src/main/java/com/example/backend_admin/dashboard/controller/DashboardController.java
- backend_admin/src/main/java/com/example/backend_admin/dashboard/model/response/GetCustomerListRes.java
- backend_admin/src/main/java/com/example/backend_admin/dashboard/service/DashboardService.java
- backend_admin/src/main/java/com/example/backend_admin/rating/service/CustomerRatingService.java
- 등급에 따른 고객들을 조회하는 기능 구현
-  총 주문 금액에 따라 내림차순으로 고객을 조회하는 기능 구현
- Customer 속성에 totalAmount(총 주문 금액) 추가
close #20 , #21
> [Feat] 고객 관리 대시보드-등급별, 금액별 필터 기능 구현(#20, #21)

- backend_admin/pom.xml
- backend_admin/src/main/java/com/example/backend_admin/email/controller/EmailController.java
- backend_admin/src/main/java/com/example/backend_admin/email/model/entity/Email.java
- backend_admin/src/main/java/com/example/backend_admin/email/repository/EmailRepository.java
- backend_admin/src/main/java/com/example/backend_admin/email/service/EmailService.java
- backend_admin/src/main/java/com/example/backend_admin/log/entity/ProductDetailLog.java
- backend_admin/src/main/java/com/example/backend_admin/log/repository/ProductDetailLogRespository.java
- backend_admin/src/main/java/com/example/backend_admin/product/model/response/GetProductRecRes.java
- backend_admin/src/main/java/com/example/backend_admin/product/service/ProductService.java
추천 상품 기능(일반) 가져와서 이메일 발송
이후 작업 사항 TODO에서 확인
> [Feat] 추천 이메일 발송 (#19)

- backend_admin/src/main/java/com/example/backend_admin/answer/controller/AnswerController.java
- backend_admin/src/main/java/com/example/backend_admin/answer/model/Answer.java
- backend_admin/src/main/java/com/example/backend_admin/answer/model/request/PostAnswerRegisterReq.java
- backend_admin/src/main/java/com/example/backend_admin/answer/model/response/PostAnswerRegisterRes.java
- backend_admin/src/main/java/com/example/backend_admin/answer/repository/AnswerRepository.java
- backend_admin/src/main/java/com/example/backend_admin/answer/service/AnswerService.java
- backend_admin/src/main/java/com/example/backend_admin/qna/controller/QnaController.java
- backend_admin/src/main/java/com/example/backend_admin/qna/model/Qna.java
- backend_admin/src/main/java/com/example/backend_admin/qna/model/request/PostQnaReadReq.java
- backend_admin/src/main/java/com/example/backend_admin/qna/model/request/PostQnaRegisterReq.java
- backend_admin/src/main/java/com/example/backend_admin/qna/model/response/GetQnaListRes.java
- backend_admin/src/main/java/com/example/backend_admin/qna/model/response/PostQnaReadRes.java
- backend_admin/src/main/java/com/example/backend_admin/qna/model/response/PostQnaRegisterRes.java
- backend_admin/src/main/java/com/example/backend_admin/qna/repository/QnaRepository.java
- backend_admin/src/main/java/com/example/backend_admin/qna/service/QnaService.java
> [Feat] 1:1문의 답변 기능 (#22, #23, #24)

- backend/src/main/java/com/example/backend/admin/model/entity/Admin.java
- backend/src/main/java/com/example/backend/admin/repository/AdminRepository.java
- backend/src/main/java/com/example/backend/answer/model/entity/Answer.java
- backend/src/main/java/com/example/backend/coupon/model/entity/Coupon.java
- backend/src/main/java/com/example/backend/qna/model/response/PostQnaReadRes.java
- backend/src/main/java/com/example/backend/qna/service/QnaService.java
답변 사용을 위해 Admin 엔티티 추가
답변이 있을 경우 답변도 함께 반환
> [Fix] 상세 조회 시 답변 조회 (#23)

- backend_admin/src/main/java/com/example/backend_admin/admin/controller/AdminController.java
- backend_admin/src/main/java/com/example/backend_admin/admin/model/request/PostAdminLevelCouponReq.java
- backend_admin/src/main/java/com/example/backend_admin/admin/model/request/PostAdminSleeperCouponReq.java
- backend_admin/src/main/java/com/example/backend_admin/admin/model/response/PostAdminSleeperCouponRes.java
- backend_admin/src/main/java/com/example/backend_admin/admin/service/AdminService.java
- backend_admin/src/main/java/com/example/backend_admin/coupon/model/request/PostCouponCreateReq.java
- backend_admin/src/main/java/com/example/backend_admin/coupon/model/response/PostCouponCreateRes.java
- backend_admin/src/main/java/com/example/backend_admin/coupon/service/CouponService.java
- backend_admin/src/main/java/com/example/backend_admin/customer/entity/Customer.java
- backend_admin/src/main/java/com/example/backend_admin/havecoupon/model/entity/request/PostHaveCouponCreateReq.java
- backend_admin/src/main/java/com/example/backend_admin/havecoupon/model/entity/response/PostHaveCouponCreateRes.java
- backend_admin/src/main/java/com/example/backend_admin/havecoupon/service/HaveCouponService.java
- backend_admin/src/main/java/com/example/backend_admin/log/repository/LoginLogRespository.java
- 등급 별로 쿠폰 발급 기능
- 장기 미접속 회원 쿠폰 발급 기능
close #16, #17
> [Feat] 조건 별로 coupon 발급 기능 구현 (#16, #17)

- backend/src/main/java/com/example/backend/havecoupon/model/response/GetHaveCouponReadRes.java
- backend/src/main/java/com/example/backend/havecoupon/service/HaveCouponService.java
- Coupon service에서의 응답 discount 추가
> [Fix] Coupon response 수정

- frontend/src/components/DetailsComponent.vue
- frontend/src/pages/OrderCompletePage.vue
- frontend/src/router/index.js
- 상품 상세 페이지에서 주문이 완료되면 주문 완료 페이지로 이동
- 주문번호, 주문일시, 상품이름, 상품 가격이 출력됨
- 홈으로 돌아가기 버튼을 누를 시 메인 페이지로 리다이렉트
close #49
> [Feat] 주문완료 페이지 (#49)

- frontend/src/components/HeaderComponent.vue
- frontend/src/pages/OrderCompletePage.vue
- frontend/src/router/index.js
> [Feat] 헤더컴포넌트 수정

- backend/src/main/java/com/example/backend/product/controller/ProductController.java
- backend/src/main/java/com/example/backend/product/service/ProductService.java
- frontend/src/components/HeaderComponent.vue
- frontend/src/components/SearchCardComponent.vue
- frontend/src/pages/MainPage.vue
- frontend/src/pages/SearchResultPage.vue
- frontend/src/router/index.js
- frontend/vue.config.js
- 헤더에 있는 검색창에 키워드로 검색
- 키워드로 검색한 결과가 /search/ 로 연결되면서 확인 가능
- 싱품 검색 백엔드 기능에서 이미지도 반환하도록 수정
close #78
> [Feat] 상품 키워드 검색 기능 구현, 검색 완료된 페이지 구현(#78) 

- backend_admin/src/main/java/com/example/backend_admin/qna/model/response/PostQnaReadRes.java
- backend_admin/src/main/java/com/example/backend_admin/qna/service/QnaService.java
> [Fix] 1:1문의 상세 조회 시 답변 추가

- backend_admin/src/main/java/com/example/backend_admin/email/service/EmailService.java
- backend_admin/target/classes/templates/mail/mail.html
- backend_admin/target/classes/templates/mail/sleeper.html
이메일 템플릿 업로드
휴면 계정 이메일 발송 코드 추가
> [Fix] 휴면 계정 이메일 추가

- backend_admin/src/main/java/com/example/backend_admin/email/service/EmailService.java
- backend_admin/target/classes/templates/mail/level.html
> [Feat] 회원 등급 쿠폰 이메일 추가 (#19)

- backend_admin/src/main/java/com/example/backend_admin/batch/scheduler/BatchScheduler.java
- backend_admin/src/main/java/com/example/backend_admin/batch/service/BatchService.java
- backend_admin/src/main/java/com/example/backend_admin/log/repository/LoginLogRespository.java
- backend_admin/target/classes/templates/mail/sleeper.html
> [Fix] 이메일 발송 스케쥴러에 추가 (#84)

- frontend_admin/src/page/QnaListPage.vue
> [Fix] wrapper 추가

- backend/src/main/java/com/example/backend/customer/model/entity/Customer.java
- backend_admin/src/main/java/com/example/backend_admin/calculate/controller/CalculateController.java
- backend_admin/src/main/java/com/example/backend_admin/calculate/model/response/GetTodayOrdersRes.java
- backend_admin/src/main/java/com/example/backend_admin/calculate/model/response/GetTodaySignupRes.java
- backend_admin/src/main/java/com/example/backend_admin/calculate/service/CalculateLogService.java
- backend_admin/src/main/java/com/example/backend_admin/calculate/service/CalculateOrdersService.java
- backend_admin/src/main/java/com/example/backend_admin/customer/repository/CustomerRepository.java
- backend_admin/src/main/java/com/example/backend_admin/orders/repository/OrdersRepository.java
- 하루 신규 유입 수, 전날 대비 신규 유입 수 계산 기능 구현 
- 하루 결제 건 수, 전날 대비 결제 건 수
- 하루 매출액, 전날 대비 매출액 계산 기능 구현
> [Feat] 메인 대시보드 기능 구현 (#113)

- frontend_admin/src/page/CustomerDetailsPage.vue
> [Feat] 회원 개인 문의 조회 (#99)

- backend_admin/src/main/java/com/example/backend_admin/qna/model/Qna.java
- backend_admin/src/main/java/com/example/backend_admin/qna/model/response/GetQnaListRes.java
- backend_admin/src/main/java/com/example/backend_admin/qna/service/QnaService.java
- 고객 상세페이지에서 개별 고객이 작성한 문의 확인을 위해 Customer idx 반환
> [Fix] 1:1 문의 개별 조회를 위한 DTO 수정

- frontend_admin/src/page/QnaListPage.vue
- frontend_admin/src/page/QnaListReadPage.vue
> [Fix] 라우터 경로 수정

- backend_admin/src/main/java/com/example/backend_admin/calculate/controller/CalculateController.java
- backend_admin/src/main/java/com/example/backend_admin/calculate/model/response/GetSleepAccountGrowthRateRes.java
- backend_admin/src/main/java/com/example/backend_admin/calculate/model/response/GetTodayLoginByThreeHour.java
- backend_admin/src/main/java/com/example/backend_admin/calculate/service/CalculateLogService.java
- backend_admin/src/main/java/com/example/backend_admin/log/repository/LoginLogRespository.java
> [Feat] 대시보드 메인페이지 집계 기능 구현 (#113)

- backend/src/main/resources/application.yml
- backend_admin/src/main/resources/application.yml
- frontend/src/components/HeaderComponent.vue
- frontend/src/pages/LoginPage.vue
- frontend/src/pages/MainPage.vue
- frontend/src/pages/SignupPage.vue
- frontend_admin/src/page/MainDashboard.vue
- 로그인, 회원가입 오류 수정
- 프론트 에러 수정
- 보유 쿠폰 @마우스엔터를 @클릭으로 변경
> [Fix] 로그인, 회원가입 오류 수정

- frontend_admin/src/page/MainDashboard.vue
> [Feat] 메인 대시보드 axios 연결 (#117)

- backend/src/main/java/com/example/backend/customer/model/response/GetCustomerListRes.java
- backend/src/main/java/com/example/backend/customer/model/response/GetCustomerReadRes.java
- backend/src/main/java/com/example/backend/customer/service/CustomerService.java
- frontend/src/components/HeaderComponent.vue
- frontend_admin/public/assets/css/style.css
- frontend_admin/src/components/NavComponent.vue
- frontend_admin/src/components/SideComponent.vue
- frontend_admin/src/page/CustomerDetailsPage.vue
- CustomerService (list, read)에 amount, level 추가
> [Feat] 대시보드 axios 구현 (#117)

- .idea/misc.xml
- backend_admin/src/main/java/com/example/backend_admin/batch/scheduler/BatchScheduler.java
- backend_admin/src/main/java/com/example/backend_admin/calculate/service/CalculateLogService.java
- backend_admin/src/main/java/com/example/backend_admin/log/repository/LoginLogRespository.java
> [Fix] 메인 페이지 집계 함수 수정 (#113)

- frontend_admin/public/assets/css/style.css
- frontend_admin/src/components/NavComponent.vue
- frontend_admin/src/page/CustomerPage.vue
> [Feat] 고객 대시보드 axios 구현 (#98)

- frontend_admin/src/page/QnaListReadPage.vue
> [Fix] 1:1 문의 답변 테스트 토큰 제거

- backend_admin/src/main/java/com/example/backend_admin/qna/controller/QnaController.java
- backend_admin/src/main/java/com/example/backend_admin/qna/service/QnaService.java
- backend_admin/src/test/java/com/example/backend_admin/qna/service/QnaServiceTest.java
- 전체 목록 조회
- 답변이 없는 문의 상세 조회
- 답변이 있는 문의 상세 조회
- 게시물이 존재하지 않을 경우
> [Test] QnaService 테스트 코드

- backend_admin/src/main/java/com/example/backend_admin/calculate/controller/CalculateController.java
- backend_admin/src/main/java/com/example/backend_admin/calculate/model/response/GetLoginTimeRes.java
- backend_admin/src/main/java/com/example/backend_admin/calculate/service/CalculateLogService.java
- backend_admin/src/main/java/com/example/backend_admin/log/repository/LoginLogRespository.java
- frontend_admin/src/components/NavComponent.vue
- frontend_admin/src/page/CustomerDetailsPage.vue
- frontend_admin/src/page/MainDashboard.vue
> [Feat] 메인페이지 시간대별 로그인, 고객 상세페이지 고객의 시간대별 로그인 프론트엔드& 백엔드 구현(#99, #113)

- backend_admin/src/main/java/com/example/backend_admin/admin/controller/AdminController.java
- backend_admin/src/main/java/com/example/backend_admin/admin/service/AdminService.java
- frontend/src/pages/QnaListPage.vue
- frontend_admin/src/App.vue
- frontend_admin/src/components/SideComponent.vue
- frontend_admin/src/page/LoginPage.vue
- frontend_admin/src/router/index.js
- frontend_admin/src/stores/useAdminStore.js
-로그인 시 로컬 스토리지에 토큰 저장
-로그인 하지 않은 사용자는 로그인 페이지 외에 다른 페이지 접근 불가
-로그인 페이지에서는 네비, 사이드 컴포넌트 안뜨게 수정
-어드민 스토어 수정
-
> [Feat] 로그인 페이지 axios 구현 (#92)

- frontend_admin/src/page/QnaListReadPage.vue
> [Fix] 1:1 문의 답변 axios 수정

- backend_admin/src/test/java/com/example/backend_admin/qna/service/QnaServiceTest.java
> [Test] 관리자 1:1 문의 테스트 코드 수정

- frontend_admin/src/page/CustomerDetailsPage.vue
- frontend_admin/src/page/MainDashboard.vue
- frontend_admin/src/page/QnaListPage.vue
- frontend_admin/src/page/QnaListReadPage.vue
> [Fix] 1:1 문의 조회

- backend/src/main/java/com/example/backend/customer/controller/CustomerController.java
- backend/src/main/java/com/example/backend/havecoupon/controller/HaveCouponController.java
- backend/src/main/java/com/example/backend/orders/controller/OrdersController.java
- backend/src/main/java/com/example/backend/orders/service/OrdersService.java
- backend/src/main/java/com/example/backend/product/controller/ProductController.java
- backend/src/main/java/com/example/backend/qna/controller/QnaController.java
- backend_admin/src/main/java/com/example/backend_admin/admin/controller/AdminController.java
- backend_admin/src/main/java/com/example/backend_admin/calculate/controller/CalculateController.java
- backend_admin/src/main/java/com/example/backend_admin/calculate/service/CalculateLogService.java
- backend_admin/src/main/java/com/example/backend_admin/calculate/service/CalculateOrdersService.java
- backend_admin/src/main/java/com/example/backend_admin/coupon/controller/CouponController.java
- backend_admin/src/main/java/com/example/backend_admin/email/controller/EmailController.java
- backend_admin/src/main/java/com/example/backend_admin/qna/controller/QnaController.java
> [Fix] 예외처리 수정

- backend/src/main/java/com/example/backend/customer/model/request/PostCustomerSignupReq.java
- backend/src/main/java/com/example/backend/customer/service/CustomerService.java
- frontend/src/components/HeaderComponent.vue
- frontend/src/pages/OrderCompletePage.vue
- frontend/src/pages/SignupPage.vue
-로그아웃 시 회원가입, 로그인 뜨고 로컬 스토리지에서 토큰 삭제하는 기능 구현
> [Fix] 로그아웃 수정 (#80)

- backend_admin/pom.xml
- backend_admin/src/main/java/com/example/backend_admin/answer/controller/AnswerController.java
- backend_admin/src/main/java/com/example/backend_admin/answer/model/request/PostAnswerRegisterReq.java
- backend_admin/src/main/java/com/example/backend_admin/answer/service/AnswerService.java
- backend_admin/src/main/java/com/example/backend_admin/utils/TokenProvider.java
- backend_admin/src/test/java/com/example/backend_admin/answer/service/AnswerServiceTest.java
- backend_admin/src/test/java/com/example/backend_admin/qna/service/QnaServiceTest.java
- 예외처리 미적용 부분 적용
- 문의 답변 테스트 코드 수정
> [Test] 관리자 1:1 문의 답변 테스트 코드 수정

- backend/pom.xml
- backend/src/main/resources/application.yml
- backend_admin/pom.xml
- backend_admin/src/main/resources/application.yml
- frontend/Dockerfile
- frontend_admin/Dockerfile
> [Fix] Dockerfile, yml 수정

- cicd/docker/Dockerfile
- cicd/k8s/backend-admin-deployment.yml
- cicd/k8s/backend-admin-service.yml
- cicd/k8s/backend-config.yml
- cicd/k8s/backend-deployment.yml
- cicd/k8s/backend-service.yml
- cicd/k8s/frontend-admin-deployment.yml
- cicd/k8s/frontend-admin-service.yml
- cicd/k8s/frontend-deployment.yml
- cicd/k8s/frontend-service.yml
- deployment, service, Dockerfile 추가
> [Docs] k8s yml 파일 추가

- backend/Dockerfile
- backend_admin/Dockerfile
> [Docs] Dockerfile 추가

- frontend/frontend-deployment.yml
> [Fix] frontend deployment 수정 

- backend_admin/src/main/resources/application.yml
- frontend_admin/nginx/default.conf
- backend_admin mariadb로 수정
- frontend_admin /api 연결 주소 수정
> [Fix] db driver, api 주소 수정

- backend/README.md
- 시스템 아키텍처 작성
- 릴레이션 스키마
- 이커머스 ERD
- 기술 스택
- 프로젝트 설명
- 이미지 추가
> [Docs] backend readme 작성

- backend_admin/pom.xml
- backend_admin/src/main/java/com/example/backend_admin/admin/service/AdminService.java
- backend_admin/src/main/java/com/example/backend_admin/batch/service/BatchService.java
- backend_admin/src/main/java/com/example/backend_admin/coupon/controller/CouponController.java
- backend_admin/src/main/java/com/example/backend_admin/coupon/model/request/PostCouponCreateReq.java
- backend_admin/src/main/java/com/example/backend_admin/coupon/service/CouponService.java
- backend_admin/src/main/java/com/example/backend_admin/coupon/service/SetCouponTargetService.java
- backend_admin/src/main/java/com/example/backend_admin/customer/repository/CustomerRepository.java
- frontend_admin/src/page/CouponPage.vue
- 쿠폰 발급 대상 선택 가능
- 쿠폰 대상 및 대상에 해당하는 쿠폰 id json 형태로 저장
- 스케쥴러를 통해 쿠폰 발급
> [Feat] 쿠폰 발급 기능

- backend_admin/src/main/resources/couponTarget.json
> [Fix] 쿠폰 발급 기능 수정

- frontend_admin/src/page/CouponPage.vue
> [Fix] 쿠폰 발급 링크 연결 수정 

- backend_admin/src/main/java/com/example/backend_admin/dashboard/controller/DashboardController.java
> [Fix] DashboardController.java 임시 주석 처리

- backend_admin/src/test/java/com/example/backend_admin/qna/service/QnaServiceTest.java
- frontend_admin/src/page/CouponPage.vue
> [Fix] Coupon 프론트, QnaTest 수정

- backend/src/main/java/com/example/backend/customer/controller/CustomerController.java
> [Fix] redirect 주소 변경

- backend/src/main/resources/application.yml
- frontend/src/components/HeaderComponent.vue
- frontend/src/pages/CategoryPage.vue
- frontend/src/pages/MainPage.vue
- frontend/src/pages/QnaListPage.vue
- frontend/src/router/index.js
- 1:1문의 내역 먼저 나오도록 수정
- 전체적인 디자인 수정
- 카테고리 페이지 연결 수정
> [Fix] 이커머스 디자인 수정

- backend/src/main/resources/application.yml
> [Fix] application.yml 수정

- backend/pom.xml
- backend/src/main/java/com/example/backend/customer/service/CustomerService.java
- backend/src/main/java/com/example/backend/orders/service/OrdersService.java
- backend/src/main/java/com/example/backend/product/service/ProductService.java
- backend/src/main/resources/logback-spring.xml
> [Feat] slf4j Logger 추가, 로그 기능 수정

- backend_admin/pom.xml
- backend_admin/src/main/java/com/example/backend_admin/elastic/controller/ElasticController.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/entity/LoginDocument.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/entity/OrdersDocument.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/entity/ProductDetailDocument.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/entity/ProductSearchDocument.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/repository/LoginDocumentRepository.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/repository/OrdersDocumentRepository.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/repository/ProductDetailDocumentRepository.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/repository/ProductSearchDocumentRepository.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/service/LoginService.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/service/OrdersService.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/service/ProductDetailService.java
- backend_admin/src/main/resources/application.yml
- Login
- Orders
- ProductDetail
- ProductSearch
> (#219) [Feat] ElasticSearch 설정, Entity, Controller, Service, Repository 추가

- backend_admin/src/main/java/com/example/backend_admin/coupon/service/CouponTargetUploadService.java
- backend_admin/src/main/java/com/example/backend_admin/coupon/service/SetCouponTargetService.java
- couponTarget.json 파일 위치 S3로 변경
> [Fix] 파일 경로 수정

- backend/src/main/java/com/example/backend/orders/controller/OrdersController.java
- backend/src/main/java/com/example/backend/product/controller/ProductController.java
- backend_admin/src/main/java/com/example/backend_admin/config/AppConfig.java
- backend_admin/src/main/java/com/example/backend_admin/dashboard/controller/CalculateController.java
- backend_admin/src/main/java/com/example/backend_admin/dashboard/service/CalculateOrdersService.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/controller/ElasticController.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/entity/LoginDocument.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/entity/OrdersDocument.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/entity/ProductDetailDocument.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/repository/LoginDocumentRepository.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/repository/OrdersDocumentRepository.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/repository/ProductDetailDocumentRepository.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/repository/ProductSearchDocumentRepository.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/service/LoginService.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/service/OrdersService.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/service/ProductDetailService.java
- 메인 대시보드 집계함수
- 고객 대시보드 집계함수
close #219
> [Feat] 관리자 페이지 집계함수 ElasticSearch 전환

- backend_admin/src/main/java/com/example/backend_admin/elastic/controller/ElasticController.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/model/dto/GetCategoryOrdersRes.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/model/dto/GetLoginTimeRes.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/model/dto/GetSleepAccountRes.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/model/dto/GetTodayLoginRes.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/model/dto/GetTodayOrdersRes.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/model/dto/GetTodaySignupRes.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/model/response/MainDashBoardRes.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/service/LoginService.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/service/OrdersService.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/service/ProductDetailService.java
- frontend_admin/src/page/CustomerDetailsPage.vue
- frontend_admin/src/page/MainDashboard.vue
- 요청을 ES로 가도록 프론트 수정
- 프론트에 맞게 DTO 변경
- 프론트에 맞게 HTTP 요청 변경
> [Feat] Elastic Search 전환 완료

- backend_admin/src/main/java/com/example/backend_admin/elastic/model/response/CustomerDetailRes.java
> [Fix] 고객 집계함수 응답 DTO 수정

- backend/src/main/java/com/example/backend/customer/model/request/PostCustomerSignupReq.java
- backend_admin/src/main/java/com/example/backend_admin/customer/entity/Customer.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/controller/ElasticCustomerController.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/model/entity/CustomerDocument.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/model/entity/LoginDocument.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/model/entity/OrdersDocument.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/model/entity/ProductDetailDocument.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/model/entity/ProductSearchDocument.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/repository/CustomerDocumentRepository.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/repository/LoginDocumentRepository.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/repository/OrdersDocumentRepository.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/repository/ProductDetailDocumentRepository.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/repository/ProductSearchDocumentRepository.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/service/ElasticCustomerService.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/service/LoginService.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/service/OrdersService.java
- backend_admin/src/main/resources/application.yml
> [Feat] Elastic Search를 이용한 고객 대시보드 필터링 및 페이징 백엔드 기능 완료 (#236) 

- backend_admin/src/main/java/com/example/backend_admin/elastic/controller/ElasticCustomerController.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/service/ElasticCustomerService.java
- backend_admin/src/main/java/com/example/backend_admin/elastic/service/OrdersService.java
- frontend_admin/src/page/CustomerPage.vue
-  고객대시보드 ES를 이용한 필터링 및 페이징 프론트엔드 개발 완료
- BaseResponse로 응답 수정
- 10명씩 보이도록 수정
- 메인 대시보드 전날 동시간대 대비 차이 수정
> [Feat] 고객대시보드 ES를 이용한 필터링 및 페이징 프론트엔드 개발 완료 (#237)

- backend_admin/src/main/java/com/example/backend_admin/customer/entity/Customer.java
- backend_admin/src/main/resources/application.yml
- backend admin 8080으로 포트 변경
- name 중복 속성 삭제
> [Fix] 포트 변경, 빌드 에러 수정

- cicd/README.md
> [Docs] CI CD README 작성

- batch/level_calculate/.gitignore
- batch/level_calculate/Dockerfile
- batch/level_calculate/mvnw
- batch/level_calculate/mvnw.cmd
- batch/level_calculate/pom.xml
- batch/level_calculate/src/main/java/com/example/demo/DemoApplication.java
- batch/level_calculate/src/main/java/com/example/demo/common/BaseException.java
- batch/level_calculate/src/main/java/com/example/demo/common/BaseResponse.java
- batch/level_calculate/src/main/java/com/example/demo/common/BaseResponseStatus.java
- batch/level_calculate/src/main/java/com/example/demo/common/BaseTimeEntity.java
- batch/level_calculate/src/main/java/com/example/demo/common/CustomerLevel.java
- batch/level_calculate/src/main/java/com/example/demo/config/QuerydslConfig.java
- batch/level_calculate/src/main/java/com/example/demo/customer/model/entity/Customer.java
- batch/level_calculate/src/main/java/com/example/demo/customer/model/entity/CustomerDocument.java
- batch/level_calculate/src/main/java/com/example/demo/customer/repository/CustomerDocumentRepository.java
- batch/level_calculate/src/main/java/com/example/demo/customer/repository/CustomerRepository.java
- batch/level_calculate/src/main/java/com/example/demo/job/CustomerLevelCalculate.java
- batch/level_calculate/src/main/java/com/example/demo/job/LevelCalculateReader.java
- batch/level_calculate/src/main/java/com/example/demo/job/LevelCalculateWriter.java
- batch/level_calculate/src/main/java/com/example/demo/login/model/entity/LoginDocument.java
- batch/level_calculate/src/main/java/com/example/demo/login/repository/LoginDocumentRepository.java
- batch/level_calculate/src/main/java/com/example/demo/orders/model/entity/OrdersDocument.java
- batch/level_calculate/src/main/java/com/example/demo/orders/repository/OrdersDocumentRepository.java
- batch/level_coupon/src/main/java/com/example/demo/havecoupon/model/entity/request/HaveCouponCreateReq.java
- batch/level_coupon/src/main/java/com/example/demo/havecoupon/service/HaveCouponService.java
- batch/level_coupon/src/main/java/com/example/demo/job/CustomerItemWriter.java
- 기존의 Rating 배치로 전환
- 쿠폰 발급 기능 수정
> [Feat] 고객 등급 계산 배치

- backend/src/main/java/com/example/backend/qna/service/QnaService.java
- frontend/src/pages/LoginPage.vue
- frontend/src/pages/QnaListPage.vue
- frontend/src/pages/QnaListReadPage.vue
- frontend/src/pages/QnaRegisterPage.vue
- frontend/src/pages/SearchResultPage.vue
- frontend/src/pages/SignupPage.vue
-조회 했을 때 문의 유형도 보이게 수정
-검색 페이지 4개씩 보이게 수정
> [Fix] 1:1 문의 상세조회 수정

- README.md
- Elastic Search
- Logstash
- Filebeat
뱃지 추가
> [Docs] README ELF 스택 뱃지 추가
